2018-09-12 12:03:27,745 ERROR: Exception on /index [GET] [in C:\Continuum\anaconda3\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Continuum\anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Continuum\anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Continuum\anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Continuum\anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Continuum\anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Continuum\anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Continuum\anaconda3\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\chikjo\Documents\Python_Projects\flask_tutorial\app\routes.py", line 42, in index
    posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "C:\Continuum\anaconda3\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "C:\Continuum\anaconda3\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\chikjo\Documents\Python_Projects\flask_tutorial\app\templates\base.html", line 73, in template
    <li><a href="{{ url_for('logout'}}">Profile</a></li>
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\chikjo\Documents\Python_Projects\flask_tutorial\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\chikjo\Documents\Python_Projects\flask_tutorial\app\templates\base.html", line 73, in template
    <li><a href="{{ url_for('logout'}}">Profile</a></li>
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 223, in parse_if
    drop_needle=True)
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 875, in subparse
    add_data(self.parse_tuple(with_condexpr=True))
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 620, in parse_tuple
    args.append(parse())
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 432, in parse_expression
    return self.parse_condexpr()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 437, in parse_condexpr
    expr1 = self.parse_or()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 450, in parse_or
    left = self.parse_and()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 459, in parse_and
    left = self.parse_not()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 470, in parse_not
    return self.parse_compare()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 474, in parse_compare
    expr = self.parse_math1()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 496, in parse_math1
    left = self.parse_concat()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 507, in parse_concat
    args = [self.parse_math2()]
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 517, in parse_math2
    left = self.parse_pow()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 528, in parse_pow
    left = self.parse_unary()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 547, in parse_unary
    node = self.parse_postfix(node)
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 676, in parse_postfix
    node = self.parse_call(node)
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 790, in parse_call
    args.append(self.parse_expression())
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 432, in parse_expression
    return self.parse_condexpr()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 437, in parse_condexpr
    expr1 = self.parse_or()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 450, in parse_or
    left = self.parse_and()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 459, in parse_and
    left = self.parse_not()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 470, in parse_not
    return self.parse_compare()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 474, in parse_compare
    expr = self.parse_math1()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 496, in parse_math1
    left = self.parse_concat()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 507, in parse_concat
    args = [self.parse_math2()]
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 517, in parse_math2
    left = self.parse_pow()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 528, in parse_pow
    left = self.parse_unary()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 546, in parse_unary
    node = self.parse_primary()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 564, in parse_primary
    next(self.stream)
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\lexer.py", line 359, in __next__
    self.current = next(self._iter)
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\lexer.py", line 562, in wrap
    for lineno, token, value in stream:
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\lexer.py", line 690, in tokeniter
    filename)
jinja2.exceptions.TemplateSyntaxError: unexpected '}', expected ')'
2018-09-12 12:05:38,442 INFO: Microblog startup [in C:\Users\chikjo\Documents\Python_Projects\flask_tutorial\app\__init__.py:49]
2018-09-12 12:05:40,577 ERROR: Exception on /navbar-fixed-top.css [GET] [in C:\Continuum\anaconda3\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Continuum\anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Continuum\anaconda3\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Continuum\anaconda3\lib\site-packages\flask\app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "C:\Continuum\anaconda3\lib\site-packages\flask\ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "C:\Continuum\anaconda3\lib\site-packages\werkzeug\routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Continuum\anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Continuum\anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Continuum\anaconda3\lib\site-packages\flask\app.py", line 1713, in handle_user_exception
    return self.handle_http_exception(e)
  File "C:\Continuum\anaconda3\lib\site-packages\flask\app.py", line 1644, in handle_http_exception
    return handler(e)
  File "C:\Users\chikjo\Documents\Python_Projects\flask_tutorial\app\errors.py", line 9, in not_found_error
    return render_templaet('404.html'), 404
NameError: name 'render_templaet' is not defined
