2018-09-13 13:07:24,994 ERROR: Exception on /favicon.ico [GET] [in C:\Continuum\anaconda3\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Continuum\anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Continuum\anaconda3\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Continuum\anaconda3\lib\site-packages\flask\app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "C:\Continuum\anaconda3\lib\site-packages\flask\ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "C:\Continuum\anaconda3\lib\site-packages\werkzeug\routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Continuum\anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Continuum\anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Continuum\anaconda3\lib\site-packages\flask\app.py", line 1713, in handle_user_exception
    return self.handle_http_exception(e)
  File "C:\Continuum\anaconda3\lib\site-packages\flask\app.py", line 1644, in handle_http_exception
    return handler(e)
  File "C:\Users\chikjo\Documents\Python_Projects\flask_tutorial\app\errors.py", line 9, in not_found_error
    return render_template('404.html'), 404
  File "C:\Continuum\anaconda3\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\chikjo\Documents\Python_Projects\flask_tutorial\app\templates\404.html", line 1, in template
    {% extends "base.html"}
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 274, in parse_extends
    node.template = self.parse_expression()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 432, in parse_expression
    return self.parse_condexpr()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 437, in parse_condexpr
    expr1 = self.parse_or()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 450, in parse_or
    left = self.parse_and()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 459, in parse_and
    left = self.parse_not()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 470, in parse_not
    return self.parse_compare()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 474, in parse_compare
    expr = self.parse_math1()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 496, in parse_math1
    left = self.parse_concat()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 507, in parse_concat
    args = [self.parse_math2()]
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 517, in parse_math2
    left = self.parse_pow()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 528, in parse_pow
    left = self.parse_unary()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 546, in parse_unary
    node = self.parse_primary()
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\parser.py", line 564, in parse_primary
    next(self.stream)
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\lexer.py", line 359, in __next__
    self.current = next(self._iter)
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\lexer.py", line 562, in wrap
    for lineno, token, value in stream:
  File "C:\Continuum\anaconda3\lib\site-packages\jinja2\lexer.py", line 683, in tokeniter
    filename)
jinja2.exceptions.TemplateSyntaxError: unexpected '}'
